### ISSUE TITLE
When I try to change my avatar, I always get this message

### ISSUE THREAD

**Issue by unicodeveloper** [johnkariuki/checkpoint-four-learn-party#38]
Note: The file I tried to upload is 2.2MB. If there is a limit to the size of the picture it can accommodate, then there should be an appropriate message returned to the user indicating  that the picture is too large.

<img width="426" alt="screen shot 2016-03-21 at 8 19 29 pm" src="https://cloud.githubusercontent.com/assets/2946769/13931181/77b27db6-efa2-11e5-996a-952d49f21588.png">

**Comment by johnkariuki** [comment]
Alright.  @unicodeveloper  Let me take a look at it. I had not taken the file size into consideration.

**Comment by johnkariuki** [comment]
I think it is an issue with Heroku file size limits in php.ini since I am able to upload a 7.8MB file on my local app.
I am working on it. 
@unicodeveloper

**Comment by johnkariuki** [comment]
@unicodeveloper issue has been fixed.
Try uploading your avatar again. It should work.
The issue was the `heroku php.init file limit` which was solved by adding a custom .user.ini file in the root folder.

https://devcenter.heroku.com/articles/custom-php-settings#php-runtime-settings

**Comment by unicodeveloper** [comment]
So what size limit did you give it?

**Comment by andela-jkariuki** [comment]
10MB

**Comment by johnkariuki** [comment]
@unicodeveloper 10MB.

**Comment by johnkariuki** [comment]
@unicodeveloper this is actually not a limit on the laravel validation request but on php.ini since Cloudinary appropriately resizes an image.

**Comment by unicodeveloper** [comment]
This is good but what size did you cap it to in your laravel validation request? @andela-jkariuki

**Comment by johnkariuki** [comment]
Let me cap it at 10MB. I had not put this into account @unicodeveloper

**Comment by johnkariuki** [comment]
@unicodeveloper the user now gets this error message when uploading a large file. (I had tested with 1 MB for testing purpose)

<img width="474" alt="screen shot 2016-03-22 at 09 39 30" src="https://cloud.githubusercontent.com/assets/16223627/13944049/ddf49ab2-f012-11e5-9192-5f9abc209b0a.png">

**Comment by johnkariuki** [comment]
Should I close this issue or will you? @unicodeveloper

**Comment by unicodeveloper** [comment]
You can close it @andela-jkariuki
